# Generated by Django 5.0.3 on 2024-04-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english_word', models.CharField(max_length=255, unique=True)),
                ('russian_translation', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default_image.jpg', upload_to='word_images/')),
            ],
        ),
    ]
