# Generated by Django 5.0.3 on 2024-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, default='word_images/default_image.jpg', upload_to='word_images/'),
        ),
    ]
